### ISSUE TITLE
Is it okay that fuzz tests fail?

### ISSUE THREAD

**Issue by felix91gr** [Bouke/DNS#15]
Hi. I enabled the fuzz tests and `swift test` always crashes. Is this okay (like, the library should fail when `Message(deserialize: data)` finds that `data` is corrupted), or is it a bug?

I'm on Linux, Swift 4.1

**Comment by felix91gr** [comment]
Ohh, I see now :)

**Comment by Bouke** [comment]
So yeah if you find additional issues, feel free to discuss them here! 👍
