### ISSUE TITLE
Unable to Use Libary

### ISSUE THREAD

**Issue by Bluesky13503** [Bouke/DNS#17]
Hello Everyone,
I am unable to use this library. would be great to get some help.

I found out, that what I need to use is resolving a DNS SRV Records.
so what I did was using the 

    func testReadMe() throws {
        // If the code below doesn't work, also update the README.md to
        // demonstrate the changes in the API.
        let request = Message(
            type: .query,
            questions: [Question(name: "_sip._tls", type: .service)]  //Changed this to Service
        )
        let requestData = try request.serialize()

        // Not shown here: send to DNS server over UDP, receive reply.
        let responseData = requestData

        // Decoding a message
        let response = try Message(deserialize: responseData)
        print(response.answers.first ?? "No answers")
    }

1. This is not using the DNS Search List, as far as I can see
2. This is not Returning any result. 

What is wrong here?

**Comment by mcfedr** [comment]
Hard to say, this library doesn't deal with the transport or resolving of DNS, just (de)serialization of packets. The use of DNS search list would be handled at the level of the dns resolver you are using, i.e. where you send the packet.
