### ISSUE TITLE
Use Custom DNS server to query from

### ISSUE THREAD

**Issue by mdeora** [Bouke/DNS#18]
How can we specify custom dns server to query from?

**Comment by mcfedr** [comment]
As in #17 - this library doesn't make requests to any server, it only parses the responses. You need to add some of your own code to send requests and receive responses

**Comment by Bouke** [comment]
I have been experimenting with adding a resolver, see also this branch: https://github.com/Bouke/DNS/tree/feature/resolver.

**Comment by mdeora** [comment]
Looks interesting, will check it out.
